apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: k8-docker
  name: k8-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      run: k8-docker
  template:
    metadata:
      labels:
        run: k8-docker
    spec:
      containers:
      - image: localhost:50000/spring-boot-docker:2.0
        name: k8-docker
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3